#!/usr/bin/env python

print('\n-----------------------')
print('INSTALL')
print('-----------------------\n')

print('install some deps here...')

print('\n-----------------------')
print('RUN SCHEMA-CHECK')
print('-----------------------\n')

print('running schema-check!\n')

print('TEST COMPLETE!\n\n')

