#!/usr/bin/env python
import os
import sys
from argparse import ArgumentParser

DIR_PATH = '/Users/rpappalardo/git/services-test-ISSUE-127'

def main(argv=None):
    options = arg_parser()

    tmp = test_types(options.project)
    print(tmp)
    parse_manifest(options.project, options.test_env)

    """
    [1]. args: retrieve project_name, test_env from user
    [2]. test_types:
         retrieve list of directories in services-test/<project_name>
         autopush/e2e-test
         autopush/loadtest
         autopush/schema-check
    [3]. in a loop, do the following:
        a. parse manifest file of each test-type
        b. execute run file for that test-type in the proper env (dev, stage, prod, etc.)
    """

def arg_parser(argv=None):
    if argv is None:
        argv = sys.argv

    conf_parser = ArgumentParser(prog='ci-test-run')

    conf_parser.add_argument("-p", "--project",
                             help="Provide a project name")
    conf_parser.add_argument("-e", "--test-env",
                             help="Provide the environment to test in\n"
                             "i.e.: dev, stage, prod")
    return conf_parser.parse_args()

def test_types(project_name):
    print(project_name)
    test_types = []
    items = os.walk(DIR_PATH).next()[1]

    return [item for item in items if not item.startswith(('_', '.'))]

def parse_manifest(project_name, test_env):
    print(test_env)
    print('parse ini file.')
    return True

# [ { 'platform': 'windows', 'test_bin': '/autopush/e2e-test/run' }, etc. ]


if __name__ == "__main__":
    main()
