#!/bin/bash


# $WORKSPACE is a Jenkins variable for project root
# if running locally, we'll set this to local project root
if [[ -z "$WORKSPACE" ]]; then 
    export WORKSPACE=.
fi
cd ${WORKSPACE}/kinto
virtualenv venv
. venv/bin/activate
pip install -r test-requirements.txt
py.test --env=stage -v config-check-test/test_kinto_signer.py

