#!/usr/bin/env python

print('\n-----------------------')
print('INSTALL')
print('-----------------------\n')

print('install some deps here...')

print('\n-----------------------')
print('RUN TEST')
print('-----------------------\n')
print('hello world.\n')

print('TEST COMPLETE!')

